GET http://localhost:5000/api/announcements?type=Miscellaneous

###

POST http://localhost:5000/api/announcements
Content-Type: application/json

{
  "type": "Miscellaneous",
  "content": "world.",
  "title": "jjj"
}

###

GET http://localhost:5000/api/announcements/5cd540790ccabc72308051dd
Content-Type: application/json

###

POST http://localhost:5000/api/announcements/5cd540790ccabc72308051dd/release

###
