export enum Gender {
	MALE = 'Male',
	FEMALE = 'Female',
	OTHER = 'Other'
}

export const ethnicities = [
	'Non-Hispanic White',
	'Black or African American',
	'Latino, Latina, or Hispanic American',
	'South Asian or Indian American',
	'East Asian or Asian American',
	'Middle Eastern or Arab American',
	'Native American or Alaskan Native',
	'Hawaiian or Pacific Islander',
	'Multiple ethnicity / Other',
	'Prefer not to answer'
];

export enum ClassYear {
	FRESHMAN = 'Freshman',
	SOPHOMORE = 'Sophomore',
	JUNIOR = 'Junior',
	SENIOR = 'Senior'
}

export const gradYears = [2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025];

export enum Referral {
	SOCIAL_MEDIA = 'Social Media',
    WEBSITE = 'Purdue Hackers Website',
    FLYERS = 'Flyers',
    CLASS = 'Class Callout',
    FRIEND = 'Friend',
    OTHER = 'Other'
}

export enum ShirtSize {
	SMALL = 'S',
    MEDIUM = 'M',
    LARGE = 'L',
    EXTRA_LARGE = 'XL',
    EXTRA_EXTRA_LARGE = 'XXL'
}

export enum Status {
	PENDING = 'Pending',
	ACCEPTED = 'Accepted',
	REJECTED = 'Rejected',
	WAITLIST = 'Waitlist'
}

export enum Major {
	'Accounting' = 'Accounting',
	'Acting' = 'Acting',
	'Actuarial Science' = 'Actuarial Science',
	'Aeronautical and Astronautical Engineering' = 'Aeronautical and Astronautical Engineering',
	'Aeronautical Engineering Technology' = 'Aeronautical Engineering Technology',
	'Aerospace Financial Analysis' = 'Aerospace Financial Analysis',
	'African American Studies' = 'African American Studies',
	'Agribusiness (multiple concentrations)' = 'Agribusiness (multiple concentrations)',
	'Agricultural Communication' = 'Agricultural Communication',
	'Agricultural Economics (multiple concentrations)' = 'Agricultural Economics (multiple concentrations)',
	'Agricultural Education' = 'Agricultural Education',
	'Agricultural Engineering' = 'Agricultural Engineering',
	'Agricultural Systems Management' = 'Agricultural Systems Management',
	'Agronomy (multiple concentrations)' = 'Agronomy (multiple concentrations)',
	'Airline Management and Operations' = 'Airline Management and Operations',
	'Airport Management and Operations' = 'Airport Management and Operations',
	'American Studies' = 'American Studies',
	'Animal Sciences (multiple concentrations)' = 'Animal Sciences (multiple concentrations)',
	'Animation' = 'Animation',
	'Anthropology' = 'Anthropology',
	'Applied Exercise and Health (Pre)' = 'Applied Exercise and Health (Pre)',
	'Applied Meteorology and Climatology' = 'Applied Meteorology and Climatology',
	'Art History' = 'Art History',
	'Asian Studies' = 'Asian Studies',
	'Athletic Training (Pre)' = 'Athletic Training (Pre)',
	'Atmospheric Science/Meteorology' = 'Atmospheric Science/Meteorology',
	'Audio Engineering Technology' = 'Audio Engineering Technology',
	'Automation and Systems Integration Engineering Technology' = 'Automation and Systems Integration Engineering Technology',
	'Aviation Management' = 'Aviation Management',
	'Biochemistry' = 'Biochemistry',
	'Biochemistry (Biology)' = 'Biochemistry (Biology)',
	'Biochemistry (Chemistry)' = 'Biochemistry (Chemistry)',
	'Biological Engineering - multiple concentrations' = 'Biological Engineering - multiple concentrations',
	'Biology' = 'Biology',
	'Biomedical Engineering' = 'Biomedical Engineering',
	'Brain and Behavioral Sciences' = 'Brain and Behavioral Sciences',
	'Building Information Modeling' = 'Building Information Modeling',
	'Cell, Molecular, and Developmental Biology' = 'Cell, Molecular, and Developmental Biology',
	'Chemical Engineering' = 'Chemical Engineering',
	'Chemistry' = 'Chemistry',
	'Chemistry - American Chemical Society' = 'Chemistry - American Chemical Society',
	'Chinese Studies' = 'Chinese Studies',
	'Civil Engineering' = 'Civil Engineering',
	'Classical Studies' = 'Classical Studies',
	'Communication, General (Pre)' = 'Communication, General (Pre)',
	'Comparative Literature' = 'Comparative Literature',
	'Computer and Information Technology' = 'Computer and Information Technology',
	'Computer Engineering' = 'Computer Engineering',
	'Computer Science' = 'Computer Science',
	'Construction Engineering' = 'Construction Engineering',
	'Construction Management Technology' = 'Construction Management Technology',
	'Creative Writing' = 'Creative Writing',
	'Crop Science' = 'Crop Science',
	'Cybersecurity' = 'Cybersecurity',
	'Data Science' = 'Data Science',
	'Data Visualization' = 'Data Visualization',
	'Design and Construction Integration' = 'Design and Construction Integration',
	'Developmental and Family Science' = 'Developmental and Family Science',
	'Early Childhood Education and Exceptional Needs' = 'Early Childhood Education and Exceptional Needs',
	'Ecology, Evolution, and Environmental Sciences' = 'Ecology, Evolution, and Environmental Sciences',
	'Economics (Pre) (College of Liberal Arts)' = 'Economics (Pre) (College of Liberal Arts)',
	'Economics (School of Management)' = 'Economics (School of Management)',
	'Effects Technical Direction' = 'Effects Technical Direction',
	'Electrical Engineering' = 'Electrical Engineering',
	'Electrical Engineering Technology' = 'Electrical Engineering Technology',
	'Elementary Education' = 'Elementary Education',
	'Engineering / Technology Teacher Education' = 'Engineering / Technology Teacher Education',
	'English' = 'English',
	'Environmental and Ecological Engineering' = 'Environmental and Ecological Engineering',
	'Environmental and Natural Resources Engineering' = 'Environmental and Natural Resources Engineering',
	'Environmental Geosciences' = 'Environmental Geosciences',
	'Environmental Health Sciences' = 'Environmental Health Sciences',
	'Environmental Studies (Pre)' = 'Environmental Studies (Pre)',
	'Exploratory Studies (for undecided students)' = 'Exploratory Studies (for undecided students)',
	'Family and Consumer Sciences Education' = 'Family and Consumer Sciences Education',
	'Farm Management' = 'Farm Management',
	'Film and Theatre Production' = 'Film and Theatre Production',
	'Film and Video Studies' = 'Film and Video Studies',
	'Finance' = 'Finance',
	'Financial Counseling and Planning' = 'Financial Counseling and Planning',
	'Fisheries and Aquatic Sciences' = 'Fisheries and Aquatic Sciences',
	'Flight (Professional Flight Technology)' = 'Flight (Professional Flight Technology)',
	'Foods and Nutrition in Business' = 'Foods and Nutrition in Business',
	'Food Science' = 'Food Science',
	'Forestry' = 'Forestry',
	'French' = 'French',
	'Game Development and Design' = 'Game Development and Design',
	'General Education: Curriculum and Instruction (non-licensure)' = 'General Education: Curriculum and Instruction (non-licensure)',
	'General Education: Educational Studies (non-licensure)' = 'General Education: Educational Studies (non-licensure)',
	'Genetic Biology' = 'Genetic Biology',
	'Geology and Geophysics' = 'Geology and Geophysics',
	'German' = 'German',
	'Global Studies' = 'Global Studies',
	'Health and Disease' = 'Health and Disease',
	'Health Sciences - Preprofessional' = 'Health Sciences - Preprofessional',
	'History' = 'History',
	'Horticulture (multiple concentrations)' = 'Horticulture (multiple concentrations)',
	'Hospitality and Tourism Management' = 'Hospitality and Tourism Management',
	'Human Resource Development' = 'Human Resource Development',
	'Human Services' = 'Human Services',
	'Industrial (Consumer Product) Design' = 'Industrial (Consumer Product) Design',
	'Industrial Engineering' = 'Industrial Engineering',
	'Industrial Engineering Technology' = 'Industrial Engineering Technology',
	'Industrial Management' = 'Industrial Management',
	'Insect Biology' = 'Insect Biology',
	'Integrated Studio Arts' = 'Integrated Studio Arts',
	'Interdisciplinary Engineering Studies' = 'Interdisciplinary Engineering Studies',
	'Interior (Space Planning) Design' = 'Interior (Space Planning) Design',
	'Italian Studies' = 'Italian Studies',
	'Japanese' = 'Japanese',
	'Jewish Studies' = 'Jewish Studies',
	'Kinesiology' = 'Kinesiology',
	'Landscape Architecture (Pre)' = 'Landscape Architecture (Pre)',
	'Law and Society' = 'Law and Society',
	'Learning Sciences in Educational Studies (non licensure)' = 'Learning Sciences in Educational Studies (non licensure)',
	'Linguistics' = 'Linguistics',
	'Management (General)' = 'Management (General)',
	'Marketing' = 'Marketing',
	'Materials Engineering' = 'Materials Engineering',
	'Mathematics' = 'Mathematics',
	'Mathematics Education' = 'Mathematics Education',
	'Mechanical Engineering' = 'Mechanical Engineering',
	'Mechanical Engineering Technology' = 'Mechanical Engineering Technology',
	'Mechatronics Engineering Technology' = 'Mechatronics Engineering Technology',
	'Medical Laboratory Sciences' = 'Medical Laboratory Sciences',
	'Medieval and Renaissance Studies' = 'Medieval and Renaissance Studies',
	'Microbiology' = 'Microbiology',
	'Multidisciplinary Engineering' = 'Multidisciplinary Engineering',
	'Natural Resources and Environmental Science (multiple concentrations)' = 'Natural Resources and Environmental Science (multiple concentrations)',
	'Network Engineering Technology' = 'Network Engineering Technology',
	'Neurobiology and Physiology' = 'Neurobiology and Physiology',
	'Nuclear Engineering' = 'Nuclear Engineering',
	'Nursing' = 'Nursing',
	'Nutrition, Fitness, and Health' = 'Nutrition, Fitness, and Health',
	'Nutrition and Dietetics' = 'Nutrition and Dietetics',
	'Nutrition and Dietetics/Nutrition, Fitness and Health (dual major)' = 'Nutrition and Dietetics/Nutrition, Fitness and Health (dual major)',
	'Nutrition Science' = 'Nutrition Science',
	'Occupational Health Science' = 'Occupational Health Science',
	'Organizational Leadership' = 'Organizational Leadership',
	'Pharmacy' = 'Pharmacy',
	'Philosophy' = 'Philosophy',
	'Physics' = 'Physics',
	'Planetary Sciences' = 'Planetary Sciences',
	'Plant Genetics, Breeding, and Biotechnology' = 'Plant Genetics, Breeding, and Biotechnology',
	'Plant Science' = 'Plant Science',
	'Political Science' = 'Political Science',
	'Predentistry' = 'Predentistry',
	'Prelaw' = 'Prelaw',
	'Premedicine' = 'Premedicine',
	'Preoccupational Therapy' = 'Preoccupational Therapy',
	'Prephysical Therapy' = 'Prephysical Therapy',
	"Prephysician's Assistant" = "Prephysician's Assistant",
	'Pre-veterinary Medicine' = 'Pre-veterinary Medicine',
	'Professional Writing' = 'Professional Writing',
	'Psychological Sciences' = 'Psychological Sciences',
	'Public Health' = 'Public Health',
	'Purdue Polytechnic Institute Statewide Programs' = 'Purdue Polytechnic Institute Statewide Programs',
	'Radiological Health Sciences - Health Physics' = 'Radiological Health Sciences - Health Physics',
	'Radiological Health Sciences - Pre-Medical Physics' = 'Radiological Health Sciences - Pre-Medical Physics',
	'Religious Studies' = 'Religious Studies',
	'Retail Management' = 'Retail Management',
	'Robotics Engineering Technology' = 'Robotics Engineering Technology',
	'Russian' = 'Russian',
	'Sales and Marketing' = 'Sales and Marketing',
	'Science Education (Biology, Chemistry, Earth/Space, Physics)' = 'Science Education (Biology, Chemistry, Earth/Space, Physics)',
	'Selling and Sales Management' = 'Selling and Sales Management',
	'Social Studies Education' = 'Social Studies Education',
	'Sociology' = 'Sociology',
	'Soil and Water Sciences' = 'Soil and Water Sciences',
	'Sound for the Performing Arts' = 'Sound for the Performing Arts',
	'Spanish' = 'Spanish',
	'Special Education: Dual Licensure in Elementary Education and Special Education - Mild Intervention' = 'Special Education: Dual Licensure in Elementary Education and Special Education - Mild Intervention',
	'Special Education: Mild and Intense Intervention P-12' = 'Special Education: Mild and Intense Intervention P-12',
	'Special Education: Mild Intervention P-12' = 'Special Education: Mild Intervention P-12',
	'Speech, Language, and Hearing Sciences' = 'Speech, Language, and Hearing Sciences',
	'Statistics - Applied Statistics' = 'Statistics - Applied Statistics',
	'Statistics with Mathematics Option' = 'Statistics with Mathematics Option',
	'Studio Arts and Technology' = 'Studio Arts and Technology',
	'Supply Chain Information and Analytics' = 'Supply Chain Information and Analytics',
	'Supply Chain Management Technology' = 'Supply Chain Management Technology',
	'Sustainable Biomaterials – Process and Product Design' = 'Sustainable Biomaterials – Process and Product Design',
	'Sustainable Food and Farming Systems' = 'Sustainable Food and Farming Systems',
	'Systems Analysis and Design' = 'Systems Analysis and Design',
	'Theatre' = 'Theatre',
	'Theatre Design and Production' = 'Theatre Design and Production',
	'Transdisciplinary Studies in Engineering Technology' = 'Transdisciplinary Studies in Engineering Technology',
	'Transdisciplinary Studies in Technology' = 'Transdisciplinary Studies in Technology',
	'Turf Management and Science' = 'Turf Management and Science',
	'Undecided Liberal Arts' = 'Undecided Liberal Arts',
	'Undecided within Engineering' = 'Undecided within Engineering',
	'Unmanned Aerial Systems' = 'Unmanned Aerial Systems',
	'UX Design' = 'UX Design',
	'Veterinary Technician or Technologist' = 'Veterinary Technician or Technologist',
	'Virtual Product Integration' = 'Virtual Product Integration',
	'Visual Arts Design Education' = 'Visual Arts Design Education',
	'Visual Arts Education' = 'Visual Arts Education',
	'Visual Communications Design' = 'Visual Communications Design',
	'Visual Effects Compositing' = 'Visual Effects Compositing',
	'Web Programming and Design' = 'Web Programming and Design',
	'Wildlife' = 'Wildlife',
	'Women’s, Gender and Sexuality Studies' = 'Women’s, Gender and Sexuality Studies'
}
